System_Parameters:
  is_debug: 'False'
  device: 'cuda:0'
  use_pretrained_model: 'False'
  Val_while_train: 'True'
  Test_while_train: 'False'
  num_workers: 2
  test: 'False'
Root:
  data_dictionary_train: 'D:/Dataset/MFNet/train-val'
  data_dictionary_val: 'D:/Dataset/MFNet/train-val'
  checkpoint_root: './Checkpoint'
  save_data: E:/2D_Test_house
  log_path: []
Data:
  data_type: 'train'
  shape: [256, 256]
  down_sample_ratio: 4
  split_sequences:
    train: ["train"]
    valid: ["test"]
  data_end:
    ir: _x
    vis: _rgb
    label:
Train:
  train_batch_size: 4
  val_batch_size: 1
  test_while_train_batch_size: 1
  test_batch_size: 1
  epoch: 300
  learning_rate: 6e-5
  decay_rate: 0.01
  decay_step:
Test:
  checkpoint_name: 'epoch_300_l1ssimgc_3type' # pretrain and test
  model_epoch: '300'
  start_epoch: 1
